# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: Ubuntu Docker-CI

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-18.04'

resources:
- repo: self

variables:
  imageName: 'massj/ubuntu1804:gcc7'

stages:
- stage: Build and Push
  displayName: Build and Push image
  jobs:  
  - job: Build and Push
    displayName: Login to DockerHub, Build and Push
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: 'login'
        containerRegistry: 'DockerHub'
    - task: Docker@2
      displayName: Build and Push an Image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: '$(imageName)'
        tags: 'gcc7'
    - task: Docker@2
      displayName: Logout of Dockerhub
      inputs:
        command: logout
        containerRegistry: dockerRegistryServiceConnection2